services:
  app: # サービス名
    build: .
    restart: always
    container_name: "app"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go/src/app
  cloudflared:
    image: cloudflare/cloudflared:latest
    depends_on:
      - app
    command: tunnel --no-autoupdate --url http://app:8080