worker_processes  1;

events {
    worker_connections  1024;
}

http {
    upstream app_backend {
        server app:8080;
    }

    upstream web_backend {
        server web:3000;
    }

    server {
        listen 80;
        server_name localhost;

        # API など、/api/ で始まるリクエストは Golang アプリへ振り分け
        location /api/ {
            proxy_pass http://app_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # それ以外のリクエストは Next.js アプリへ振り分け
        location / {
            proxy_pass http://web_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
